### ISSUE TITLE
Стратегии мобов

### ISSUE THREAD

**Issue by ilchuk96** [ilchuk96/RogueLike#8]
Они работают, но плохо. 
TODO: рефактор - сейчас мы просто "ищем" игрока его в радиусе 4 клеток, надо же просто смотреть, где он (т.к. теперь это 1 команда, а не перебор).
TODO: поменять стратегии. Если зажать "убегающего" в угол, он там и будет сидеть, хотя, очевидно, ему выгоднее уйти в бок (если не поняли, спросите меня по телефону, мне сейчас лень объяснять).

**Comment by StanislavSychev** [comment]
Убегающий просто не думая бежит от игрока, он еще может врезаться в другого бота и начать от паники атаковать его). Мне кажется это забавное поведение, и гонятся за ним долго не придется.
